In [3]:
import random

import tensorflow as tf
import numpy as np

In [4]:
print(tf.__version__)

2.20.0


# Tensors

tf.constant(value, shape, dtype, name)

In [19]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [20]:
vector = tf.constant([7, 8])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 8])>

In [28]:
matrix = tf.constant([
    [
        [1, 0],
        [0, 1]
    ],
    [
        [1, 0],
        [0, 1]
    ]
])
matrix

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 0],
        [0, 1]],

       [[1, 0],
        [0, 1]]])>

In [3]:
from collections import defaultdict


In [4]:
arr = [1,3,1,2,3,5,6,4,2,1,3]

In [54]:
def make(arr):
    print(arr)
    uni = set()

    result = []

    for i in range(0, len(arr)):
        sum = 0
        for j in range(0, i + 1):
            sum += count(arr[j: i + 1])
        result.append(sum)
    return result

In [55]:
import random
def count(arr):
    return len(set(arr))

In [65]:
ans = make([x - 0 if x <= random.randint(1, 100) else 3  for x in range(100)])
for i in ans:
    print(i, end = " ")

[0, 1, 2, 3, 4, 5, 6, 7, 3, 9, 10, 11, 12, 13, 14, 15, 3, 17, 18, 19, 20, 21, 22, 23, 3, 25, 26, 27, 28, 29, 30, 31, 3, 33, 34, 35, 36, 37, 38, 3, 40, 3, 42, 3, 44, 3, 46, 3, 48, 3, 50, 51, 52, 3, 3, 3, 56, 3, 58, 59, 60, 61, 3, 63, 3, 65, 66, 3, 68, 3, 3, 71, 3, 73, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 91, 3, 93, 3, 3, 3, 3, 3, 3]
1 3 6 10 15 21 28 36 41 51 62 74 87 101 116 132 140 158 177 197 218 240 263 287 295 321 348 376 405 435 466 498 506 540 575 611 648 686 725 732 773 775 818 820 865 867 914 916 965 967 1018 1070 1123 1127 1128 1129 1186 1188 1247 1307 1368 1430 1435 1499 1501 1567 1634 1637 1706 1708 1709 1781 1783 1857 1859 1860 1861 1862 1863 1864 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1967 1969 2063 2065 2066 2067 2068 2069 2070 

In [69]:
ans = make("1 2 3 4 5 6 7 8 4 9 10 11 12 13 14 15 4 16 17 18 19 20 21 22 4 23 24 25 26 27 28 29 4 30 31 32 33 34 35 4 36 4 37 4 38 4 39 4 40 4 41 42 43 4 4 4 44 4 45 46 47 48 4 49 4 50 51 4 52 4 4 53 4 54 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 55 4 56 4 4 4 4 4 4".split(" "))
for i in ans:
    print(i, end = " ")
print("\n",len(ans))

['1', '2', '3', '4', '5', '6', '7', '8', '4', '9', '10', '11', '12', '13', '14', '15', '4', '16', '17', '18', '19', '20', '21', '22', '4', '23', '24', '25', '26', '27', '28', '29', '4', '30', '31', '32', '33', '34', '35', '4', '36', '4', '37', '4', '38', '4', '39', '4', '40', '4', '41', '42', '43', '4', '4', '4', '44', '4', '45', '46', '47', '48', '4', '49', '4', '50', '51', '4', '52', '4', '4', '53', '4', '54', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '55', '4', '56', '4', '4', '4', '4', '4', '4']
1 3 6 10 15 21 28 36 41 51 62 74 87 101 116 132 140 158 177 197 218 240 263 287 295 321 348 376 405 435 466 498 506 540 575 611 648 686 725 732 773 775 818 820 865 867 914 916 965 967 1018 1070 1123 1127 1128 1129 1186 1188 1247 1307 1368 1430 1435 1499 1501 1567 1634 1637 1706 1708 1709 1781 1783 1857 1859 1860 1861 1862 1863 1864 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1967 1969 2063 2065 2066 2067 2068 2069 2070 
 100


In [1]:
def bn(a):
    return str(bin(a))[2::]

In [5]:
bn(11)

'1011'

In [6]:
bn(10)

'1010'

In [40]:
def rm(s):
    for i in range(len(s) - 1, -1,-1):
        if(s[i] == "1"):
            return s[0:i + 1]
    return s


In [51]:
rm("11")

11


'11'

In [60]:
for i in range(1, 101):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [58]:
for i in range(1,100):
    print((bn(int(bn(i), 2) ^ int(bn(i)[::-1], 2))))

0
11
0
101
0
101
0
1001
0
1111
110
1111
110
1001
0
10001
0
11011
1010
10001
0
11011
1010
11011
1010
10001
0
11011
1010
10001
0
100001
0
110011
10010
101101
1100
111111
11110
101101
1100
111111
11110
100001
0
110011
10010
110011
10010
100001
0
111111
11110
101101
1100
111111
11110
101101
1100
110011
10010
100001
0
1000001
0
1100011
100010
1010101
10100
1110111
110110
1000001
0
1100011
100010
1010101
10100
1110111
110110
1010101
10100
1110111
110110
1000001
0
1100011
100010
1010101
10100
1110111
110110
1000001
0
1100011
100010
1100011
100010
1000001
0


In [ ]:
t = int(input())

for i in range(t):
    n = int(input())
    s = rm(str(bin(n))[2::])

    if(s[::-1] == s):
        print("YES")
    else:
        print("NO")